# Generated by Django 5.2.10 on 2026-01-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(max_length=200, verbose_name='Sarlavha (Rus)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Sarlavha (Ingliz)')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Rasm')),
                ('description_uz', models.TextField(verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.TextField(verbose_name='Tavsif (Rus)')),
                ('description_en', models.TextField(verbose_name='Tavsif (Ingliz)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, upload_to='blog_videos/', verbose_name='Video fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name="Nomi (O'zbek)")),
                ('name_ru', models.CharField(max_length=200, verbose_name='Nomi (Rus)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Nomi (Ingliz)')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('short_description_uz', models.TextField(max_length=300, verbose_name="Qisqa tavsif (O'zbek)")),
                ('short_description_ru', models.TextField(max_length=300, verbose_name='Qisqa tavsif (Rus)')),
                ('short_description_en', models.TextField(max_length=300, verbose_name='Qisqa tavsif (Ingliz)')),
                ('full_description_uz', models.TextField(verbose_name="To'liq tavsif (O'zbek)")),
                ('full_description_ru', models.TextField(verbose_name="To'liq tavsif (Rus)")),
                ('full_description_en', models.TextField(verbose_name="To'liq tavsif (Ingliz)")),
                ('client_uz', models.CharField(blank=True, max_length=200, verbose_name="Kim uchun qilingan (O'zbek)")),
                ('client_ru', models.CharField(blank=True, max_length=200, verbose_name='Kim uchun qilingan (Rus)')),
                ('client_en', models.CharField(blank=True, max_length=200, verbose_name='Kim uchun qilingan (Ingliz)')),
                ('url', models.URLField(blank=True, verbose_name='URL manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Til nomi (O'zbek)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Til nomi (Rus)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Til nomi (Ingliz)')),
                ('percentage', models.IntegerField(verbose_name='Foiz (0-100)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['order'],
            },
        ),
    ]
